# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('start', models.DecimalField(decimal_places=2, max_digits=5)),
                ('first', models.DecimalField(decimal_places=2, max_digits=5)),
                ('second', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waitting', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
