# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181123_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True)),
                ('hour', models.TimeField(auto_now=True)),
                ('people', models.IntegerField()),
                ('miles', models.DecimalField(decimal_places=2, max_digits=5)),
                ('toll', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='waitting',
            new_name='waiting',
        ),
    ]
