# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 00:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181124_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
