# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181124_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='day',
            field=models.DateField(),
        ),
    ]
