# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181124_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='day',
        ),
        migrations.RemoveField(
            model_name='journey',
            name='hour',
        ),
        migrations.AddField(
            model_name='journey',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
