# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181126_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journey',
            name='hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
