# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181126_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='name',
            field=models.CharField(default='quote', max_length=25),
        ),
    ]
