# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_journey_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='slug',
        ),
    ]
