# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-16 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_journey_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
