# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-16 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_tariff_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
