# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20181216_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='first_label',
            field=models.CharField(default='The next one tenth of a mile', max_length=100),
        ),
        migrations.AddField(
            model_name='tariff',
            name='second_label',
            field=models.CharField(default='For each subsequent one fifth of a mile', max_length=100),
        ),
        migrations.AddField(
            model_name='tariff',
            name='start_label',
            field=models.CharField(default='For any distance up to one tenth of a mile', max_length=100),
        ),
        migrations.AddField(
            model_name='tariff',
            name='waiting_label',
            field=models.CharField(default='Each completed period of 60 seconds waiting time', max_length=100),
        ),
    ]
